version: '3'

services:
  redis:
    container_name: cache
    image: redis:redis
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"
    expose:
      - 6379

  web-typescript:
    container_name: web-typescript
    image: sample-react-typescript
    build: react-type-www
    hostname: react-typescript-sample
    ports:
      - "3004:3000"
  web:
    container_name: web
    image: sample-react
    build: angular-type-www
    hostname: reactsmaple
    ports:
      - "3003:3000"
  app:
    container_name: spring-app
    image: spring-shortener
    build: ./app
    hostname: shortener
    ports:
      - "8080:8080"
    links:
      - redis

  test:
    container_name: sample-react-test
    build: angular-type-www
    volumes:
      - '.:/web/app'
      - '/web/app/node_modules'
    environment:
      - CI=true
    command: npm test
